services:
  web:
    # image: ghcr.io/cedar2025/xboard:new
    build: .
    volumes:
      - ./:/www/
    environment:
      - docker=true
    depends_on:
      - redis
    network_mode: host
    command: php artisan octane:start --server="swoole" --port=7001
    restart: on-failure
  horizon:
    image: ghcr.io/cedar2025/xboard:new
    volumes:
      - ./:/www/
    restart: on-failure
    network_mode: host
    command: php artisan horizon
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --appendfsync everysec
    restart: unless-stopped
    volumes:
      - ./.docker/.data/redis:/data
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
